### ISSUE TITLE
ros2 daemon causes cli issue when switching distros

### ISSUE THREAD

**Issue by mikeferguson** [osrf/ros2_test_cases#1056]
To reproduce:

 * System: Ubuntu 22.04, AMD64. Following issue occurs with both cyclone and fastrtps.
 * In Humble - "ros2 launch demo_nodes_cpp talker_listener.launch.py"
 * In Humble - "ros2 node list" then works
 * Shut all that down, switch to an Iron environment
 * In Iron - "ros2 launch demo_nodes_cpp talker_listener_launch.py" (note the . is now a _ before launch)
 * In Iron - "ros2 node list" fails - traceback is below
 * To get things working - "ros2 daemon stop" - and then "ros2 node list" works properly in Iron

```
ubr@ubr1:~/iron$ ros2 node list
Traceback (most recent call last):
  File "/opt/ros/iron/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.25.1', 'console_scripts', 'ros2')())
  File "/opt/ros/iron/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/iron/lib/python3.10/site-packages/ros2node/command/node.py", line 37, in main
    return extension.main(args=args)
  File "/opt/ros/iron/lib/python3.10/site-packages/ros2node/verb/list.py", line 38, in main
    node_names = get_node_names(node=node, include_hidden_nodes=args.all)
  File "/opt/ros/iron/lib/python3.10/site-packages/ros2node/api/__init__.py", line 61, in get_node_names
    node_names_and_namespaces = node.get_node_names_and_namespaces()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'rclpy._rclpy_pybind11.RCLError'>:Failed to get node names: empty node name returned by the RMW layer, at ./src/rcl/graph.c:360">
```

**Comment by mikeferguson** [comment]
@kscottz - as discussed on Twitter

**Comment by clalancette** [comment]
Can you please open this up on https://github.com/ros2/ros2 (unfortunately GitHub won't let me transfer it across organizations)?  This is a problem, but it is not a new one and not specific to Iron.  Thanks.
